export const unitlessCssProperties = [
  "borderImageSlice",
  "borderImageOutset",
  "borderImageWidth",
  "fontWeight",
  "lineHeight",
  "opacity",
  "orphans",
  "tabSize",
  "widows",
  "zIndex",
  "zoom",

  // svg
  "fillOpacity",
  "floodOpacity",
  "stopOpacity",
  "strokeDasharray",
  "strokeDashoffset",
  "strokeMiterLimit",
  "strokeOpacity",
  "strokeWidth",

  "animationIterationCount",
  "boxFlex",
  "boxFlexGroup",
  "boxOrdinalGroup",
  "columnCount",
  "flex",
  "flexGrow",
  "flexPositive",
  "flexShrink",
  "gridRow",
  "gridColumn",
  "order",
  "lineClamp",
  "gridRowEnd",
  "gridRowStart",
  "gridColumnEnd",
  "gridColumnStart",
];
